name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Repo
        env:
          PUBLIC_REPO: "andrawpt/portfolio"
          TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          # Konfigurasi remote untuk repo public dengan autentikasi token
          git remote add public-target "https://\({TOKEN}@github.com/\){PUBLIC_REPO}.git"
          
          # Push branch main dari private ke public (force push memastikan selalu identik)
          git push public-target main --force
