name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Public Repo
        env:
          PUBLIC_REPO: "andrawpt/portfolio"
          TOKEN: ${{ secrets.SYNC_PAT }}
        run: |
          git remote add public-target "https://x-access-token:\({TOKEN}@github.com/\){PUBLIC_REPO}.git"
          git push public-target main --force
